spring.application.name=ECIReserves

spring.data.mongodb.uri=mongodb+srv://jesjc1508:12345678a.@ecireserves.pdky6.mongodb.net/?retryWrites=true&w=majority&appName=ECIReserves
spring.data.mongodb.database=ECIReserves
